spring:
  config:
    activate:
      on-profile: "local"
app:
  name: "local-app-service"
---
spring:
  config:
    activate:
      on-profile: "dev"
app:
  name: "dev-app-service"
server:
  port: 80
---
spring:
  config:
    activate:
      on-profile: "prod"
app:
  name: "prod-app-service"  
server:
  port: 80