spring:
  application:
    name: user-service
  config:
    activate:
      on-profile: "local"
server:
  port: 8101
---
spring:
  config:
    activate:
      on-profile: "dev"
server:
  port: 80
---
spring:
  config:
    activate:
      on-profile: "prod"
server:
  port: 80
